Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  # Run Ansible from the Vagrant VM
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
  config.vm.synced_folder ".", "/usr/src", type: "rsync",
    rsync__exclude: ".git/"
  config.vm.provision "file", source: "~/.gpg", destination: "~/.gpg"
end
