name: Deploy Zig Package
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to Gemfury
    runs-on: rapid-ubuntu-20
    steps:
      - uses: actions/checkout@v2
      - name: Build Image and Deploy
        run: docker build -f Dockerfile --target deploy --build-arg --build-arg GFKEY='${{ secrets.GFKEY }}' -t zig:${{ github.sha }} .
