name: Deploy Zig Package
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    name: Push to Gemfury
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Image and Deploy
        run: ./build_and_deploy.sh
        env:
          GFKEY_PUSH: ${{ secrets.GFKEY_PUSH }}
